# Generated by Django 4.2.7 on 2026-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='supports_vision',
            field=models.BooleanField(default=False, help_text='该模型是否支持图像识别（如硅基流动的Qwen2-VL等视觉模型）', verbose_name='支持多模态'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='multimodal_mode',
            field=models.BooleanField(default=False, help_text='是否使用多模态（图像+文本）生成模式', verbose_name='多模态模式'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='page_images_base64',
            field=models.JSONField(blank=True, help_text='PDF各页面渲染后的Base64图片数据 [{"page": 1, "data": "...", "media_type": "image/jpeg"}]', null=True, verbose_name='页面图片Base64数据'),
        ),
    ]
