# Generated by Django 4.2.7 on 2026-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0003_aimodelconfig_supports_vision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='version_ids',
            field=models.JSONField(blank=True, default=list, help_text='生成用例时选择的版本ID列表', verbose_name='关联版本ID列表'),
        ),
    ]
