# Generated by Django 4.2.7 on 2026-06-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0004_add_version_ids_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='clarification_answers',
            field=models.JSONField(blank=True, default=list, help_text='用户对澄清问题的回答 [{"question_id": 1, "question": "...", "answer": "..."}]', verbose_name='用户澄清回答'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='clarification_questions',
            field=models.JSONField(blank=True, default=list, help_text='AI分析需求后提出的澄清问题 [{"id": 1, "question": "..."}]', verbose_name='AI澄清问题列表'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='clarifier_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarifier_tasks', to='requirement_analysis.aimodelconfig', verbose_name='澄清模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='clarifier_prompt_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarifier_tasks', to='requirement_analysis.promptconfig', verbose_name='澄清提示词配置'),
        ),
        migrations.AlterField(
            model_name='promptconfig',
            name='prompt_type',
            field=models.CharField(choices=[('writer', '用例编写提示词'), ('reviewer', '用例评审提示词'), ('clarifier', '需求澄清提示词')], max_length=20, verbose_name='提示词类型'),
        ),
    ]
