# Generated by Django 4.2.7 on 2026-06-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0005_add_clarification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='reviser_model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviser_tasks', to='requirement_analysis.aimodelconfig', verbose_name='改进模型配置'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='reviser_prompt_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviser_tasks', to='requirement_analysis.promptconfig', verbose_name='改进提示词配置'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('clarifier', '需求澄清专家'), ('reviser', '用例改进专家'), ('browser_use_text', 'Browser Use - 文本模式')], max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='promptconfig',
            name='prompt_type',
            field=models.CharField(choices=[('writer', '用例编写提示词'), ('reviewer', '用例评审提示词'), ('clarifier', '需求澄清提示词'), ('reviser', '用例改进提示词')], max_length=20, verbose_name='提示词类型'),
        ),
    ]
