# Generated by Django 4.2.7 on 2026-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0006_add_reviser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='knowledge_base',
            field=models.TextField(blank=True, help_text='生成用例时从项目知识背景复制的快照，用于 AI 生成时理解业务上下文', verbose_name='项目知识背景快照'),
        ),
    ]
