# Generated by Django 4.2.7 on 2026-06-22 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_add_function_module'),
        ('requirement_analysis', '0007_add_knowledge_base_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='function_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_tasks', to='versions.functionmodule', verbose_name='关联功能模块'),
        ),
    ]
