# Generated by Django 4.2.7 on 2026-07-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0008_add_function_module_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='pipeline_stage',
            field=models.CharField(choices=[('initiated', '已创建'), ('clarifying', '澄清中'), ('awaiting_answers', '待回答'), ('answers_ready', '答案已就绪'), ('generating', '生成中'), ('generated', '已生成'), ('reviewing', '评审中'), ('reviewed', '已评审'), ('revising', '改进中'), ('completed', '已完成'), ('failed', '失败')], default='initiated', help_text='追踪生成流程的细粒度阶段，用于断点续传', max_length=20, verbose_name='流水线阶段'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('clarifier', '需求澄清专家'), ('reviser', '用例改进专家'), ('extractor', '需求文档提取专家'), ('browser_use_text', 'Browser Use - 文本模式')], max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='promptconfig',
            name='prompt_type',
            field=models.CharField(choices=[('writer', '用例编写提示词'), ('reviewer', '用例评审提示词'), ('clarifier', '需求澄清提示词'), ('reviser', '用例改进提示词'), ('extractor', '需求文档提取提示词')], max_length=20, verbose_name='提示词类型'),
        ),
    ]
