# Generated by Django 4.2.7 on 2026-07-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0009_testcasegenerationtask_pipeline_stage_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE testcase_generation_task
                SET pipeline_stage = CASE
                    WHEN status = 'pending' THEN 'initiated'
                    WHEN status = 'generating' THEN 'generating'
                    WHEN status = 'reviewing' THEN 'reviewing'
                    WHEN status = 'revising' THEN 'revising'
                    WHEN status = 'completed' THEN 'completed'
                    WHEN status = 'failed' THEN 'failed'
                    WHEN status = 'cancelled' THEN 'failed'
                    ELSE 'initiated'
                END
                WHERE pipeline_stage = 'initiated'
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
