# Generated by Django 4.2.7 on 2026-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0010_set_pipeline_stage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('clarifier', '需求澄清专家'), ('reviser', '用例改进专家'), ('extractor', '需求文档提取专家'), ('browser_use_text', 'Browser Use - 文本模式'), ('app_automation_vision', 'APP自动化-VLM视觉模型')], max_length=30, verbose_name='角色'),
        ),
    ]
