# Generated by Django 4.2.7 on 2026-07-22 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_knowledge_base_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0011_add_app_automation_vision_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModaoImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('url', models.URLField(max_length=1000, verbose_name='墨刀URL')),
                ('data', models.JSONField(help_text='{canvases: [...], images: [...]}', verbose_name='导入数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modao_imports', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modao_imports', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '墨刀导入',
                'verbose_name_plural': '墨刀导入',
                'db_table': 'modao_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
