# Generated by Django 4.2.7 on 2026-07-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0012_add_modao_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaoimport',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Celery任务ID'),
        ),
        migrations.AddField(
            model_name='modaoimport',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='modaoimport',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='进度(0-100)'),
        ),
        migrations.AddField(
            model_name='modaoimport',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('importing', '导入中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='modaoimport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='modaoimport',
            name='data',
            field=models.JSONField(default=dict, help_text='{canvases: [...], screenshots: [...]}', verbose_name='导入数据'),
        ),
    ]
