# Generated by Django 4.2.7 on 2026-09-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0014_modaoimport_stage_progress_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='modao_canvas_snapshot',
            field=models.JSONField(blank=True, help_text='从墨刀生成用例时记录用到的画布 [{name, screenshot_url, texts, folder, width, height}]，用于冒烟用例生成，不被完成清理', null=True, verbose_name='墨刀画布快照'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('clarifier', '需求澄清专家'), ('reviser', '用例改进专家'), ('extractor', '需求文档提取专家'), ('smoke_generate', '冒烟流程生成专家'), ('browser_use_text', 'Browser Use - 文本模式'), ('app_automation_vision', 'APP自动化-VLM视觉模型')], max_length=30, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='promptconfig',
            name='prompt_type',
            field=models.CharField(choices=[('writer', '用例编写提示词'), ('reviewer', '用例评审提示词'), ('clarifier', '需求澄清提示词'), ('reviser', '用例改进提示词'), ('extractor', '需求文档提取提示词'), ('smoke_generate', '冒烟流程生成提示词')], max_length=20, verbose_name='提示词类型'),
        ),
    ]
