# Generated by Django 4.2.7 on 2026-09-04 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0015_testcasegenerationtask_modao_canvas_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='用例标题')),
                ('module_names', models.JSONField(blank=True, default=list, verbose_name='模块列表')),
                ('source_type', models.CharField(choices=[('modao', '墨刀导入'), ('task', '生成任务'), ('manual', '手动')], default='modao', max_length=20, verbose_name='来源类型')),
                ('source_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='来源引用')),
                ('modules_snapshot', models.JSONField(blank=True, default=list, help_text='[{name, canvases:[{name, screenshot_url, texts, folder, width, height}]}]，供重新生成', verbose_name='模块画布快照')),
                ('steps', models.JSONField(blank=True, default=list, help_text='[{no, step, expected}]', verbose_name='步骤')),
                ('preconditions', models.CharField(blank=True, default='', max_length=500, verbose_name='前置条件')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='generating', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(0-100)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('merged_from_ids', models.JSONField(blank=True, default=list, verbose_name='合并来源记录id')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '冒烟测试用例',
                'verbose_name_plural': '冒烟测试用例',
                'db_table': 'smoke_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
