# Generated by Django 4.2.7 on 2026-09-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_knowledge_base_updated_at_and_more'),
        ('requirement_analysis', '0016_smokecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='smokecase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smoke_cases', to='projects.project', verbose_name='关联项目'),
        ),
    ]
