# Generated by Django 4.2.7 on 2026-09-16 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_project_knowledge_base_updated_at_and_more'),
        ('requirement_analysis', '0017_smokecase_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxureImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('url', models.URLField(max_length=1000, verbose_name='入口URL')),
                ('data', models.JSONField(default=dict, help_text='{import_id, pages: [...]}', verbose_name='导入数据')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('importing', '导入中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(0-100)')),
                ('stage', models.CharField(blank=True, default='', max_length=30, verbose_name='当前阶段')),
                ('progress_detail', models.JSONField(blank=True, default=dict, verbose_name='进度明细')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Celery任务ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='axure_imports', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='axure_imports', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'Axure原型导入',
                'verbose_name_plural': 'Axure原型导入',
                'db_table': 'axure_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
