# Generated by Django 4.2.7 on 2026-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='knowledge_base',
            field=models.TextField(blank=True, help_text='项目的背景知识，用于 AI 生成测试用例时理解业务上下文。支持长文本。', verbose_name='知识背景'),
        ),
    ]
