# Generated by Django 4.2.7 on 2026-06-29 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_add_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='knowledge_base_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='知识背景更新时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='knowledge_base_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_knowledge_bases', to=settings.AUTH_USER_MODEL, verbose_name='知识背景更新人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='knowledge_base',
            field=models.TextField(blank=True, help_text='项目的背景知识，用于 AI 生成测试用例时理解业务上下文。支持 Markdown 格式。', verbose_name='知识背景'),
        ),
    ]
