# Generated by Django 4.2.7 on 2026-08-20 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_host', models.CharField(default='imap.qiye.aliyun.com', max_length=255, verbose_name='IMAP服务器')),
                ('imap_port', models.IntegerField(default=993, verbose_name='IMAP端口')),
                ('imap_user', models.CharField(blank=True, default='', max_length=255, verbose_name='IMAP账号')),
                ('imap_password', models.CharField(blank=True, default='', max_length=512, verbose_name='IMAP密码')),
                ('imap_timeout', models.IntegerField(default=20, verbose_name='IMAP超时(秒)')),
                ('backend_host', models.CharField(default='192.168.1.110', max_length=255, verbose_name='推送后台地址')),
                ('backend_port', models.IntegerField(default=8015, verbose_name='推送后台端口')),
                ('push_cookie', models.TextField(blank=True, default='', verbose_name='推送后台Cookie')),
                ('tesseract_path', models.CharField(blank=True, default='', max_length=512, verbose_name='Tesseract路径(可选)')),
                ('last_uid', models.BigIntegerField(blank=True, null=True, verbose_name='最近处理邮件UID')),
                ('last_date', models.CharField(blank=True, default='', max_length=64, verbose_name='最近处理邮件日期')),
                ('last_problems', models.IntegerField(default=0, verbose_name='最近处理问题数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '工具合集配置',
                'verbose_name_plural': '工具合集配置',
                'db_table': 'toolbox_config',
            },
        ),
        migrations.CreateModel(
            name='PushCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('force', models.BooleanField(default=False, verbose_name='强制重查')),
                ('log', models.TextField(blank=True, default='', verbose_name='运行日志')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='结果摘要')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '推送对比运行记录',
                'verbose_name_plural': '推送对比运行记录',
                'db_table': 'toolbox_push_check_run',
                'ordering': ['-started_at'],
            },
        ),
    ]
