# Generated by Django 4.2.7 on 2026-08-24 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('status', models.CharField(choices=[('pending', '待监听'), ('ok', '已收到·对比通过'), ('fail', '已收到·对比不一致'), ('timeout', '超时未收到')], default='pending', max_length=10, verbose_name='状态')),
                ('mail_uid', models.BigIntegerField(blank=True, null=True, verbose_name='邮件UID')),
                ('mail_subject', models.CharField(blank=True, default='', max_length=255, verbose_name='邮件标题')),
                ('ocr_text', models.TextField(blank=True, default='', verbose_name='OCR原文')),
                ('parsed_fields', models.JSONField(blank=True, default=dict, verbose_name='解析字段')),
                ('backend_record', models.JSONField(blank=True, default=dict, verbose_name='后台记录')),
                ('diffs', models.JSONField(blank=True, default=list, verbose_name='差异列表')),
                ('log', models.TextField(blank=True, default='', verbose_name='检查日志')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '同步确认记录',
                'verbose_name_plural': '同步确认记录',
                'db_table': 'toolbox_sync_check_run',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SyncCheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用自动监听')),
                ('interval_minutes', models.IntegerField(default=15, verbose_name='检查间隔(分钟)')),
                ('deadline_time', models.CharField(default='18:30', max_length=8, verbose_name='当天截止时间(HH:MM)')),
                ('mail_subject', models.CharField(default='回复：【测试需求】关于常规PUSH的测试需求', max_length=255, verbose_name='邮件标题关键词')),
                ('mail_body_keyword', models.CharField(default='已同步至线上', max_length=100, verbose_name='正文关键词')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='上次检查时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '同步确认配置',
                'verbose_name_plural': '同步确认配置',
                'db_table': 'toolbox_sync_check_config',
            },
        ),
    ]
