# Generated by Django 4.2.7 on 2026-08-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_synccheckrun_synccheckconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccheckconfig',
            name='require_push_activity',
            field=models.BooleanField(default=True, help_text='当天无推送对比记录且无测试需求排期邮件时，不监听、不报超时', verbose_name='当天无推送活动时跳过监听'),
        ),
    ]
