# Generated by Django 4.2.7 on 2026-08-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_synccheckconfig_require_push_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synccheckconfig',
            name='require_push_activity',
            field=models.BooleanField(default=True, help_text='当天无推送对比运行记录时，不监听、不报超时', verbose_name='当天无推送活动时跳过监听'),
        ),
    ]
