# Generated by Django 4.2.7 on 2026-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0004_alter_synccheckconfig_require_push_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccheckconfig',
            name='enable_dingtalk_notify',
            field=models.BooleanField(default=False, help_text='对比不一致或超时未收到时，通过统一通知配置中的钉钉机器人推送', verbose_name='异常钉钉通知'),
        ),
        migrations.AddField(
            model_name='synccheckrun',
            name='notify_sent_status',
            field=models.CharField(blank=True, default='', help_text='当天已推送钉钉的异常状态，用于去重', max_length=10, verbose_name='已通知的异常状态'),
        ),
    ]
