# Generated by Django 4.2.7 on 2026-08-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0005_synccheckconfig_enable_dingtalk_notify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccheckconfig',
            name='extract_mode',
            field=models.CharField(choices=[('ocr', 'OCR识别'), ('vision_fallback', '视觉模型优先·OCR回退')], default='vision_fallback', help_text='视觉模型从截图提取字段（复用 TestHub Agent 配置的模型），失败自动回退 OCR', max_length=20, verbose_name='截图提取方式'),
        ),
    ]
