# Generated by Django 4.2.7 on 2026-08-27 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolbox', '0006_synccheckconfig_extract_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('unreplied_count', models.IntegerField(default=0, verbose_name='未回复数量')),
                ('ad_unreplied_count', models.IntegerField(default=0, verbose_name='广告未回复数量')),
                ('unresolved', models.JSONField(blank=True, default=list, help_text='[{subject,sender,send_time,ad,is_replied,key}]', verbose_name='未回复列表')),
                ('notified_keys', models.JSONField(blank=True, default=list, help_text='当天已推送钉钉的归一化主题，用于去重', verbose_name='已通知主题')),
                ('log', models.TextField(blank=True, default='', verbose_name='检查日志')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配置回复提醒记录',
                'verbose_name_plural': '配置回复提醒记录',
                'db_table': 'toolbox_reply_check_run',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReplyCheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用自动监听')),
                ('interval_minutes', models.IntegerField(default=15, verbose_name='检查间隔(分钟)')),
                ('qc_recipient_keywords', models.CharField(default='品管部,qc@youloft.com', help_text='逗号分隔，匹配 To/CC 的显示名或地址，任一命中即算收件人有品管部', max_length=255, verbose_name='品管部收件人关键字')),
                ('body_keyword', models.CharField(default='请QC检查', max_length=100, verbose_name='正文关键字')),
                ('title_keywords', models.CharField(default='配置,广告,测试需求', help_text='逗号分隔，标题命中任一即纳入', max_length=255, verbose_name='标题关键字')),
                ('ad_keyword', models.CharField(default='广告', max_length=50, verbose_name='广告关键字')),
                ('notify_threshold_minutes', models.IntegerField(default=30, verbose_name='非广告提醒阈值(分钟)')),
                ('enable_dingtalk_notify', models.BooleanField(default=True, help_text='未回复配置邮件通过「统一通知配置」中的钉钉机器人推送', verbose_name='钉钉通知')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='上次检查时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '配置回复提醒配置',
                'verbose_name_plural': '配置回复提醒配置',
                'db_table': 'toolbox_reply_check_config',
            },
        ),
    ]
