# Generated by Django 4.2.7 on 2026-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0007_replycheckrun_replycheckconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycheckconfig',
            name='ad_keyword',
            field=models.CharField(default='广告', help_text='逗号分隔，标题命中任一即视为广告并立即提醒', max_length=255, verbose_name='广告关键字'),
        ),
    ]
