# Generated by Django 4.2.7 on 2026-08-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0008_alter_replycheckconfig_ad_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycheckconfig',
            name='body_keyword',
            field=models.CharField(default='请QC检查', help_text='逗号分隔，正文任一命中即纳入', max_length=255, verbose_name='正文关键字'),
        ),
    ]
