# Generated by Django 4.2.7 on 2026-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_add_function_module_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='execution_status',
            field=models.CharField(blank=True, choices=[('passed', '通过'), ('failed', '不通过')], max_length=10, null=True, verbose_name='执行状态'),
        ),
    ]
