# Generated by Django 4.2.7 on 2026-09-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_testcaseexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='scene_type',
            field=models.CharField(blank=True, choices=[('main_flow', '主流程'), ('exception', '异常'), ('boundary', '边界'), ('permission', '权限'), ('risk', '风险')], default='', help_text='主流程/异常/边界/权限/风险，用于筛选与排序', max_length=20, verbose_name='场景类型'),
        ),
    ]
