# Generated by Django 4.2.7 on 2026-09-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_add_scene_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_smoke',
            field=models.BooleanField(default=False, help_text='标记为冒烟测试用例', verbose_name='冒烟用例'),
        ),
    ]
