# Generated by Django 4.2.7 on 2026-06-22 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_knowledge_base'),
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, verbose_name='模块描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_modules', to='projects.project', verbose_name='所属项目')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='versions.version', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '功能模块',
                'verbose_name_plural': '功能模块',
                'db_table': 'function_modules',
                'ordering': ['version', 'name'],
                'unique_together': {('version', 'name')},
            },
        ),
    ]
