# Generated by Django 4.2.7 on 2026-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='base_url',
            field=models.CharField(blank=True, default='', help_text='相对路径接口自动拼接此前缀，如 http://dev.com:8080', max_length=500, verbose_name='基础URL'),
        ),
        migrations.AddField(
            model_name='environment',
            name='default_headers',
            field=models.JSONField(default=dict, help_text='所有接口自动携带的请求头，接口自身可覆盖', verbose_name='默认请求头'),
        ),
        migrations.AddField(
            model_name='environment',
            name='default_params',
            field=models.JSONField(default=dict, help_text='所有接口自动携带的URL参数，接口自身可覆盖', verbose_name='默认URL参数'),
        ),
    ]
