# Generated by Django 4.2.7 on 2026-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0004_link_main_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuiterequest',
            options={'ordering': ['order'], 'verbose_name': '套件用例', 'verbose_name_plural': '套件用例'},
        ),
        migrations.AlterUniqueTogether(
            name='testsuiterequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='body',
            field=models.JSONField(blank=True, null=True, verbose_name='请求体覆盖'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='用例描述'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='extract_rules',
            field=models.JSONField(default=list, verbose_name='响应变量提取规则'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='请求头覆盖'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='用例名称'),
        ),
        migrations.AddField(
            model_name='testsuiterequest',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='参数覆盖'),
        ),
    ]
