# Generated by Django 4.2.7 on 2026-08-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0005_alter_testsuiterequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='api_testing.environment', verbose_name='默认环境'),
        ),
    ]
