# Generated by Django 4.2.7 on 2026-07-27 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('siliconflow', '硅基流动'), ('openai', 'OpenAI'), ('other', '其他')], max_length=20, verbose_name='模型提供商')),
                ('model_name', models.CharField(default='qwen-plus', max_length=200, verbose_name='模型名称')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('base_url', models.URLField(blank=True, help_text='OpenAI兼容接口地址，留空使用默认', max_length=500, verbose_name='API Base URL')),
                ('max_tokens', models.IntegerField(default=8192, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('is_active', models.BooleanField(default=True, help_text='启用后 Agent 将使用此配置', verbose_name='是否启用')),
                ('system_prompt_extra', models.TextField(blank=True, help_text='追加到 Agent 系统提示词末尾的自定义内容', verbose_name='额外系统提示词')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent配置',
                'verbose_name_plural': 'Agent配置',
                'db_table': 'agent_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='difyconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dify配置（已废弃）', 'verbose_name_plural': 'Dify配置（已废弃）'},
        ),
    ]
