# Generated by Django 4.2.7 on 2026-07-28 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_add_agent_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于调用的唯一标识，如: swagger-import', max_length=100, unique=True, verbose_name='技能标识')),
                ('display_name', models.CharField(help_text='如: Swagger 文档导入', max_length=200, verbose_name='显示名称')),
                ('description', models.CharField(help_text='在 Skill 列表中展示的一句话说明', max_length=500, verbose_name='简要描述')),
                ('instructions', models.TextField(help_text='注入到 Agent 系统提示词的指令内容，告诉 Agent 如何完成这个任务', verbose_name='执行指令')),
                ('tools', models.JSONField(blank=True, default=list, help_text='该 Skill 可用的工具列表，空列表表示使用全部工具', verbose_name='可用工具')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Agent 技能',
                'verbose_name_plural': 'Agent 技能',
                'db_table': 'agent_skills',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
