# Generated by Django 4.2.7 on 2026-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_add_agent_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='max_tool_calls',
            field=models.IntegerField(default=20, help_text='Agent 单轮对话最多调用的工具次数，复杂任务可调大', verbose_name='单轮最大工具调用次数'),
        ),
    ]
