# Generated by Django 4.2.7 on 2026-07-28 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_agentconfig_max_tool_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('upload', '用户上传'), ('output', 'Agent 产出')], max_length=10, verbose_name='来源')),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=1000, verbose_name='存储路径')),
                ('file_url', models.CharField(max_length=1000, verbose_name='访问URL')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('content_type', models.CharField(blank=True, max_length=200, verbose_name='MIME类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assistant.assistantsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'Agent 文件',
                'verbose_name_plural': 'Agent 文件',
                'db_table': 'agent_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
