# Generated by Django 4.2.7 on 2026-07-29 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_knowledge_base_updated_at_and_more'),
        ('assistant', '0006_add_agent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_sessions', to='projects.project', verbose_name='关联项目'),
        ),
    ]
