# Generated by Django 4.2.7 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_assistantsession_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='api_protocol',
            field=models.CharField(
                choices=[('auto', '自动探测'),
                         ('responses', 'Responses API'),
                         ('chat_completions', 'Chat Completions')],
                default='auto',
                help_text='自动探测优先使用 Responses API，失败自动降级 Chat Completions',
                max_length=20,
                verbose_name='接入协议'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='provider',
            field=models.CharField(
                choices=[('deepseek', 'DeepSeek'),
                         ('qwen', '通义千问'),
                         ('siliconflow', '硅基流动'),
                         ('zhipu', '智谱'),
                         ('openai', 'OpenAI'),
                         ('other', '其他')],
                max_length=20,
                verbose_name='模型提供商'),
        ),
    ]
