# Generated by Django 4.2.7 on 2026-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_agentconfig_api_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='tool_groups',
            field=models.JSONField(blank=True, default=list, help_text='按后台功能模块启用工具，空表示全部启用', verbose_name='启用工具组'),
        ),
    ]
