# Generated by Django 4.2.7 on 2026-08-31 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0010_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', '新增'), ('updated', '更新'), ('new_version', '新增版本'), ('deleted', '软删除'), ('restored', '恢复')], max_length=20, verbose_name='操作类型')),
                ('summary', models.TextField(help_text='变更内容的一句话描述', verbose_name='摘要')),
                ('session_id', models.CharField(blank=True, help_text='从哪个智能助手会话触发的（如果是 AI 更新）', max_length=200, verbose_name='触发的会话ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '知识库变更日志',
                'verbose_name_plural': '知识库变更日志',
                'db_table': 'knowledge_update_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='knowledge_c_knowled_52d5cd_idx',
            old_name='knowledge_c_knowled_5e6f1f_idx',
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='bm25_tokens',
            field=models.JSONField(blank=True, default=list, help_text='jieba 分词后的 token 列表，用于 BM25 索引', verbose_name='BM25分词结果'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False 表示软删除（被新版本替代）', verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='指向替代本 chunk 的新版本 chunk（用于版本链）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='assistant.knowledgechunk', verbose_name='被哪个新版本替代'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='version',
            field=models.IntegerField(default=1, help_text='同 path 下递增；1 为原始版本', verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_bases_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['knowledge_base', 'is_active'], name='knowledge_c_knowled_b7905b_idx'),
        ),
        migrations.AddField(
            model_name='knowledgeupdatelog',
            name='chunk',
            field=models.ForeignKey(blank=True, help_text='新版本的 chunk_id（删除时为被删的 chunk）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_logs', to='assistant.knowledgechunk', verbose_name='关联分块'),
        ),
        migrations.AddField(
            model_name='knowledgeupdatelog',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='assistant.knowledgebase', verbose_name='所属知识库'),
        ),
        migrations.AddField(
            model_name='knowledgeupdatelog',
            name='superseded_chunk',
            field=models.ForeignKey(blank=True, help_text='被新版本替代的旧 chunk_id（仅 new_version 时有值）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_logs', to='assistant.knowledgechunk', verbose_name='被替代的分块'),
        ),
        migrations.AddField(
            model_name='knowledgeupdatelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_update_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddIndex(
            model_name='knowledgeupdatelog',
            index=models.Index(fields=['knowledge_base', '-created_at'], name='knowledge_u_knowled_86ab5e_idx'),
        ),
    ]
