# Generated by Django 4.2.7 on 2026-07-09 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0011_add_app_automation_vision_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidsceneCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='用例描述')),
                ('ai_prompt', models.TextField(help_text='自然语言描述的测试步骤，每行一步', verbose_name='AI测试步骤')),
                ('max_steps', models.IntegerField(default=30, help_text='AI自动决策的最大操作步数', verbose_name='最大执行步数')),
                ('action_delay', models.FloatField(default=0.5, help_text='每次操作之间的等待时间', verbose_name='操作间隔(秒)')),
                ('app_package', models.CharField(blank=True, default='', help_text='如 com.example.app', max_length=255, verbose_name='Android包名/iOS Bundle ID')),
                ('app_activity', models.CharField(blank=True, default='', help_text='仅Android需要，iOS留空', max_length=255, verbose_name='启动Activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ai_model_config', models.ForeignKey(blank=True, help_text='Midscene执行时使用的VLM视觉模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midscene_cases', to='requirement_analysis.aimodelconfig', verbose_name='AI模型配置')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_midscene_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Midscene用例',
                'verbose_name_plural': 'Midscene用例',
                'db_table': 'midscene_cases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MidsceneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='平台类型')),
                ('device_id', models.CharField(max_length=255, unique=True, verbose_name='设备标识')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('available', '可用'), ('locked', '已锁定')], default='offline', max_length=20, verbose_name='状态')),
                ('android_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Android版本')),
                ('adb_serial', models.CharField(blank=True, default='', max_length=255, verbose_name='ADB序列号')),
                ('ios_version', models.CharField(blank=True, default='', max_length=50, verbose_name='iOS版本')),
                ('tidevice_udid', models.CharField(blank=True, default='', max_length=255, verbose_name='tidevice UDID')),
                ('wda_host', models.CharField(blank=True, default='', help_text='iOS WDA的HTTP地址，如 127.0.0.1:8100', max_length=255, verbose_name='WebDriverAgent地址')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('max_lock_time', models.IntegerField(default=28800, help_text='超过此时间自动解锁，默认8小时', verbose_name='最大锁定时间(秒)')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址')),
                ('port', models.IntegerField(default=5555, verbose_name='端口')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_midscene_devices', to=settings.AUTH_USER_MODEL, verbose_name='锁定用户')),
            ],
            options={
                'verbose_name': 'Midscene设备',
                'verbose_name_plural': 'Midscene设备',
                'db_table': 'midscene_devices',
                'ordering': ['platform', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MidsceneProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('members', models.ManyToManyField(blank=True, related_name='midscene_member_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midscene_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': 'Midscene项目',
                'verbose_name_plural': 'Midscene项目',
                'db_table': 'midscene_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MidsceneExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200, verbose_name='用例名称快照')),
                ('platform', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], default='', max_length=20, verbose_name='平台')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('stopped', '已停止'), ('error', '异常')], default='pending', max_length=20, verbose_name='执行状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(default=0, verbose_name='执行时长(秒)')),
                ('model_config_snapshot', models.JSONField(default=dict, verbose_name='AI模型快照')),
                ('report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Midscene报告路径')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步数')),
                ('passed_steps', models.IntegerField(default=0, verbose_name='通过步数')),
                ('failed_steps', models.IntegerField(default=0, verbose_name='失败步数')),
                ('steps_detail', models.JSONField(default=list, help_text='每一步的截图、AI推理、结果', verbose_name='步骤详情')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.midscenedevice', verbose_name='执行设备')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midscene_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('midscene_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='ui_automation.midscenecase', verbose_name='关联用例')),
            ],
            options={
                'verbose_name': 'Midscene执行记录',
                'verbose_name_plural': 'Midscene执行记录',
                'db_table': 'midscene_execution_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='midscenecase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midscene_cases', to='ui_automation.midsceneproject', verbose_name='所属项目'),
        ),
    ]
