# Generated by Django 4.2.7 on 2026-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_add_midscene_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='midsceneproject',
            name='default_app_package',
            field=models.CharField(blank=True, default='', help_text='Android包名或iOS Bundle ID，执行时自动启动', max_length=255, verbose_name='默认应用包名'),
        ),
    ]
