# Generated by Django 4.2.7 on 2026-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0004_add_project_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='midscenecase',
            name='ai_act_context',
            field=models.TextField(blank=True, default='', help_text='每次VLM调用都会附加此提示，如"遇到权限弹窗先点允许"', verbose_name='全局背景提示'),
        ),
    ]
