# Generated by Django 4.2.7 on 2026-07-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0005_add_ai_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='midsceneexecutionrecord',
            name='auto_plan',
            field=models.BooleanField(default=False, help_text='开启后VLM自动将复杂指令拆解为多步执行', verbose_name='智能规划模式'),
        ),
    ]
