# Generated by Django 4.2.7 on 2026-07-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0006_add_auto_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='midsceneproject',
            name='default_ios_bundle_id',
            field=models.CharField(blank=True, default='', help_text='iOS应用Bundle Identifier，如 com.example.app', max_length=255, verbose_name='iOS Bundle ID'),
        ),
        migrations.AlterField(
            model_name='midsceneproject',
            name='default_app_package',
            field=models.CharField(blank=True, default='', help_text='Android应用包名，如 com.example.app', max_length=255, verbose_name='Android包名'),
        ),
    ]
