# Generated by Django 4.2.7 on 2026-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0007_add_ios_bundle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='midscenecase',
            name='replay_data',
            field=models.JSONField(blank=True, default=None, help_text='录制成功后的回放脚本，包含设备信息、步骤动作和pHash校验值', null=True, verbose_name='回放数据'),
        ),
    ]
