# Generated by Django 4.2.7 on 2026-08-11 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0009_link_main_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidsceneCaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件夹名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_midscene_folders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ui_automation.midscenecasefolder', verbose_name='父文件夹')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midscene_folders', to='ui_automation.midsceneproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Midscene用例文件夹',
                'verbose_name_plural': 'Midscene用例文件夹',
                'db_table': 'midscene_case_folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='midscenecase',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='将用例归入文件夹，删除文件夹后用例回到未分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midscene_cases', to='ui_automation.midscenecasefolder', verbose_name='所属文件夹'),
        ),
    ]
