# Generated by Django 4.2.7 on 2026-08-21 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0010_midscene_case_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midsceneexecutionrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('stopping', '停止中'), ('passed', '通过'), ('failed', '失败'), ('stopped', '已停止'), ('error', '异常')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
        migrations.CreateModel(
            name='MidsceneAppPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='应用名称')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='平台类型')),
                ('file', models.FileField(max_length=500, upload_to='midscene/packages/%Y%m/', verbose_name='安装包文件')),
                ('package_name', models.CharField(blank=True, default='', help_text='Android包名或iOS Bundle ID', max_length=255, verbose_name='包名/Bundle ID')),
                ('version_name', models.CharField(blank=True, default='', help_text='如 2.1.0', max_length=100, verbose_name='版本名')),
                ('version_code', models.CharField(blank=True, default='', help_text='Android versionCode / iOS Build', max_length=100, verbose_name='版本号')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('md5', models.CharField(blank=True, default='', max_length=32, verbose_name='文件MD5')),
                ('description', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_midscene_packages', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': 'Midscene安装包',
                'verbose_name_plural': 'Midscene安装包管理',
                'db_table': 'midscene_app_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MidsceneAppInstallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '安装中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='安装状态')),
                ('options', models.JSONField(default=dict, help_text='覆盖安装/降级/装完启动等选项快照', verbose_name='安装选项')),
                ('log', models.TextField(blank=True, default='', verbose_name='安装日志')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(default=0, verbose_name='安装时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_midscene_installs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_records', to='ui_automation.midscenedevice', verbose_name='安装设备')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_records', to='ui_automation.midsceneapppackage', verbose_name='安装包')),
            ],
            options={
                'verbose_name': 'Midscene安装记录',
                'verbose_name_plural': 'Midscene安装记录',
                'db_table': 'midscene_app_install_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='midsceneapppackage',
            index=models.Index(fields=['platform', 'package_name'], name='midscene_ap_platfor_4aaffd_idx'),
        ),
    ]
