# Generated by Django 4.2.7 on 2026-08-25 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0011_alter_midsceneexecutionrecord_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidsceneGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_locate', models.BooleanField(blank=True, help_text='null=不覆盖，跟随环境变量 AIACT_USE_LOCATE（默认开）', null=True, verbose_name='AI两阶段定位开关')),
                ('use_deep_locate', models.CharField(blank=True, choices=[('', '不覆盖（跟随环境变量/默认）'), ('off', '关闭'), ('auto', '自动升级（默认）'), ('on', '强制深度定位')], default='', help_text='off/auto/on；空=不覆盖，跟随环境变量 AIACT_USE_DEEP_LOCATE（默认 auto）', max_length=10, verbose_name='深度定位模式')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_midscene_global_config', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'Midscene全局引擎配置',
                'verbose_name_plural': 'Midscene全局引擎配置',
                'db_table': 'midscene_global_config',
            },
        ),
    ]
