# Generated by Django 4.2.7 on 2026-08-31 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0012_midsceneglobalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidsceneSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='编排名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='编排描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_midscene_sequences', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midscene_sequences', to='ui_automation.midsceneproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Midscene用例编排',
                'verbose_name_plural': 'Midscene用例编排',
                'db_table': 'midscene_sequences',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MidsceneSequenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=200, verbose_name='编排名称快照')),
                ('platform', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], default='', max_length=20, verbose_name='平台')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('stopping', '停止中'), ('passed', '通过'), ('failed', '失败'), ('stopped', '已停止'), ('error', '异常')], default='pending', max_length=20, verbose_name='执行状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步数')),
                ('passed_steps', models.IntegerField(default=0, verbose_name='通过步数')),
                ('failed_steps', models.IntegerField(default=0, verbose_name='失败步数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(default=0, verbose_name='执行时长(秒)')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.midscenedevice', verbose_name='执行设备')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midscene_sequence_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ui_automation.midscenesequence', verbose_name='所属编排')),
            ],
            options={
                'verbose_name': 'Midscene编排执行',
                'verbose_name_plural': 'Midscene编排执行',
                'db_table': 'midscene_sequence_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MidsceneSequenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('clear_relaunch', models.BooleanField(default=False, help_text='开启则清数据+重启；关闭则接着上一项状态（可复用登录态）', verbose_name='执行前清数据并重启')),
                ('break_on_fail', models.BooleanField(default=True, verbose_name='失败即中止整条链')),
                ('replay_mode', models.CharField(choices=[('auto', '按设备自动匹配'), ('fixed', '固定脚本')], default='auto', max_length=10, verbose_name='回放脚本选择')),
                ('replay_index', models.IntegerField(default=0, help_text='仅 replay_mode=fixed 时生效，0=最新录制', verbose_name='固定回放脚本索引')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_items', to='ui_automation.midscenecase', verbose_name='用例')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ui_automation.midscenesequence', verbose_name='所属编排')),
            ],
            options={
                'verbose_name': 'Midscene编排项',
                'verbose_name_plural': 'Midscene编排项',
                'db_table': 'midscene_sequence_items',
                'ordering': ['sequence', 'order'],
            },
        ),
        migrations.AddField(
            model_name='midsceneexecutionrecord',
            name='sequence_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='ui_automation.midscenesequencerun', verbose_name='所属编排执行'),
        ),
    ]
