# Generated by Django 4.2.7 on 2026-08-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0013_midscenesequence_midscenesequencerun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midscenesequence',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='将编排归入文件夹，便于按功能组织；删除文件夹后编排回到未分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midscene_sequences', to='ui_automation.midscenecasefolder', verbose_name='所属文件夹'),
        ),
        migrations.AlterField(
            model_name='midsceneexecutionrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('stopping', '停止中'), ('passed', '通过'), ('failed', '失败'), ('stopped', '已停止'), ('skipped', '已跳过'), ('error', '异常')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='midscenesequencerun',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('stopping', '停止中'), ('passed', '通过'), ('failed', '失败'), ('stopped', '已停止'), ('skipped', '已跳过'), ('error', '异常')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
    ]
