# Generated by Django 4.2.7 on 2026-09-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0014_midscenesequence_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midscenesequenceitem',
            name='install_package',
            field=models.ForeignKey(blank=True, help_text='执行本项前覆盖安装该包并启动；不选则沿用链级默认包或当前已装版本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_items', to='ui_automation.midsceneapppackage', verbose_name='安装包（可选）'),
        ),
    ]
