# Generated by Django 4.2.7 on 2026-09-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0015_midscenesequenceitem_install_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='midscenedevice',
            name='agent_host',
            field=models.CharField(blank=True, default='', help_text='上报该设备的 agent 所在机器名', max_length=255, verbose_name='来源机器'),
        ),
        migrations.AddField(
            model_name='midscenedevice',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='agent 最近一次上报时间；超时会被判为离线', null=True, verbose_name='最近心跳'),
        ),
    ]
